const cat = {
    tvAndAudio: "tvAndAudio",
    tvBox: "tvBox",
    airPod: "airPod",
    powerTools: "powerTools",
    headphones: "headphones",
    cellPhones: "cellPhones",
    smartWatches: "smartWatches",
    gameAndVideo: "gameAndVideo",
    robotClean: "robotClean",
    sportWatches: "sportWatches",
    tablets: "tablets",
    computersAndLaptop: "computersAndLaptop",
    camerasAndPhotos: "camerasAndPhotos",
  };
  export const categories = [
    {
      id: 1001,
      name: "TV & Audio",
      image: "https://uandu.com.ng/wp-content/uploads/2021/11/2-7.jpg",
      description: "Smart Television with lastest features for home and work",
      _base: "tvAndAudio",
    },
    {
      id: 1002,
      name: "TV Box",
      image: "https://m.media-amazon.com/images/I/71Wt7x-dwYL._AC_SL1500_.jpg",
      description: "Watch on-demand videos, video content sites, play games, and watch regular network shows on big screen",
      _base: "tvBox",
    },
    {
      id: 1003,
      name: "Air Pod",
      image: "https://media.product.which.co.uk/prod/images/original/f1acc580a87b-apple-airpods-pro-2-sr17275-0876-00-front-1178x589-1.jpg",
      description: "Listen to your favorite song as you work",
      _base: "airPod",
    },
    {
      id: 1004,
      name: "Head Phones",
      image: "https://cdn1.smartprix.com/rx-iI7b4faoZ-w280-h280/skullcandy-grom-wire.jpg",
      description: "Enjoy bass music and vibes to your mood",
      _base: "headPhones",
    },
    {
      id: 1005,
      name: "Cell Phones",
      image: "https://cdn.tmobile.com/content/dam/t-mobile/en-p/cell-phones/apple/Apple-iPhone-16-Pro/Desert-Titanium/Apple-iPhone-16-Pro-Desert-Titanium-thumbnail.png",
      description: "Do amazing things with your phone at ease",
      _base: "cellPhones",
    },
    {
      id: 1006,
      name: "Smart Watches",
      image: "https://www-konga-com-res.cloudinary.com/f_auto,fl_lossy,dpr_3.0,q_auto/media/catalog/product/H/V/197813_1673038803.jpg",
      description: "Perform other actions with your wristwatch in order to reduce stress",
      _base: "smartWatches",
    },
    {
      id: 1007,
      name: "Game & Video",
      image: "https://www.digitaltrends.com/wp-content/uploads/2023/11/ps5-on-table.jpg?p=1",
      description: "Enjoy your favorite game with its lastest graphics",
      _base: "gameAndVideo",
    },
    {
      id: 1008,
      name: "Robot Clean",
      image: "https://cdn.mos.cms.futurecdn.net/JkwinQ5YkGVLW9ew6wuSUL-415-80.png",
      description: "Robot that clean the floor, keeping germs far from you.",
      _base: "robotClean",
    },
    {
      id: 1009,
      name: "Sport Watches",
      image: "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/07/27297/1.jpg?7709",
      description: "Check your heart beat and others as you work out to keep fit",
      _base: "sportWatches",
    },
    {
      id: 1010,
      name: "Tablets",
      image: "https://static1.anpoimages.com/wordpress/wp-content/uploads/2023/07/lenovo-tab-p12.jpeg",
      description: "Do amazing things with your tablets as you enjoy your life",
      _base: "tablets",
    },
    {
      id: 1011,
      name: "Computer & Laptop",
      image: "https://cdn.thewirecutter.com/wp-content/media/2023/06/bestlaptops-2048px-9765.jpg",
      description: "Work and solve problems at your pace with your laptop and computer",
      _base: "computerAndLaptop",
    },
    {
      id: 1012,
      name: "Cameras & Photos",
      image: "https://cdn.mos.cms.futurecdn.net/4wpKrH93D37dDPTisdqGy4.jpg",
      description: "Taking HD photos and video with your cameras, capture every moment of your life",
      _base: "camerasAndPhotos",
    },
  ];
  
  export const highlightsProducts = [
    {
      _id: 3001,
      name: "Hot Deals at Best Prices",
      title: "From #20,000.00",
      buttonTitle: "Browse Deals",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtCzXu-6yPgcjgztE_jVUwVjbaSGWrjV6WuA&s",
      _base: "/product",
      color: "#000000",
    },
    {
      _id: 3002,
      name: "Golden Iphone 16 Pro",
      title: "From #2,000,000.00",
      buttonTitle: "Shop Cellphone",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDKbrVcO9dWXDQZ8AnJfs2OIqny6VQiaHflg&s",
      _base: "/category/cellPhones",
      color: "#ffffff",
    },
    {
      _id: 3003,
      name: "20,000 mAh Power Bank",
      title: "From #25,000.00",
      buttonTitle: "Shop Now",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP3m7kyDrM8ZGGEAQYGNgKukJzua3OTsTBlw&s",
      _base: "/product",
      color: "#ffffff",
    },
  ];
  
  export const blogsData = [
    {
      _id: 4001,
      image: "https://i.ibb.co/XbQf5HS/blogOne.webp",
      title: "iPhone 15 rear camera design will be available",
      _base: "Technology",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
    },
    {
      _id: 4002,
      image: "https://i.ibb.co/wzNpcwp/blogTwo.webp",
      title: "Setup your surround sound speaker",
      _base: "Samrt thing",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
    },
    {
      _id: 4003,
      image: "https://i.ibb.co/prdZ3s8/blog-Three.webp",
      title: "Hook up a receiver for your home theater",
      _base: "Life style",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
    },
  ];
  
  export const products = [
    {
      _id: 2001,
      name: "Divoom Tivoo Portable Bluetooth Speaker Smart Clock Alarm Pixel Art DIY By App LED Light Sign In Decoration Unique Gift",
      images: [
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 600,
      discountedPrice: 580,
      quantity: 1,
      rating: 4.5,
      reviews: 50,
      category: "TV & Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Samsung",
      isStock: true,
      overView: "Blutooth Speaker",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2002,
      name: "Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band",
      images: [
        "https://i.ibb.co/2tCN9cy/watch-Three.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 250,
      discountedPrice: 180,
      quantity: 1,
      rating: 4.8,
      reviews: 80,
      category: "Smart Watches",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Samsung",
      isStock: true,
      overView: "Smart health watch",
      isNew: false,
      _base: cat?.smartWatches,
    },
    {
      _id: 2003,
      name: "Fitness M3 Color Screen Smart Sport Bracelet Activity Running Tracker Heart Rate For Children Men Women Watch For IOS Android",
      images: [
        "https://i.ibb.co/NrG9wxw/sport-Watch.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 650,
      discountedPrice: 570,
      quantity: 1,
      rating: 4.2,
      reviews: 30,
      category: "Sport Watches",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "MI Exclusive",
      isStock: true,
      overView: "Smart health watch",
      isNew: true,
      _base: cat?.sportWatches,
    },
    {
      _id: 2004,
      name: "SJ8 Air 1290P 4K 60fps Action Camera WIFI Remote Control Waterproof Sports DV FPV Camera",
      images: [
        "https://i.ibb.co/bQ59C0n/wifi-Camera.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 400,
      discountedPrice: 350,
      quantity: 1,
      rating: 4.2,
      reviews: 120,
      category: "Camera & Photos",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: false,
      overView: "Cameras & Photos",
      isNew: false,
      _base: cat?.camerasAndPhotos,
    },
    {
      _id: 2005,
      name: "Redmi Xiaoai Speaker Play 2.4GHz 1.75 Inch Voice Remote Control Music Player Bluetooth 4.2 Mi Speaker For Android Iphone",
      images: [
        "https://i.ibb.co/tqYyH3G/speaker.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 90,
      discountedPrice: 80,
      quantity: 1,
      rating: 4.2,
      reviews: 20,
      category: "TV & Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Blutooth Speaker",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2006,
      name: "Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band",
      images: [
        "https://i.ibb.co/1TJp88p/smart-Watch.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 300,
      discountedPrice: 280,
      quantity: 1,
      rating: 4.8,
      reviews: 110,
      category: "Smart Watches",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Smart health watch",
      isNew: false,
      _base: cat.smartWatches,
    },
    {
      _id: 2007,
      name: "Kinganda BT513 Foldable Bluetooth Headphones With Mic",
      images: [
        "https://i.ibb.co/qs8yhPB/headphone.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 600,
      discountedPrice: 550,
      quantity: 1,
      rating: 4,
      reviews: 60,
      category: "Headphones & Speakers",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Microphones",
      isNew: true,
      _base: cat.headphones,
    },
    {
      _id: 2008,
      name: "New Product Form Lapbook Light Handlift Business Office Game Ben EDP 13.5 In – Black China",
      images: [
        "https://i.ibb.co/RCHWqkS/laptop.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 1100,
      discountedPrice: 1080,
      quantity: 1,
      rating: 4.7,
      reviews: 190,
      category: "Computers & Laptops",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Computer Components",
      isNew: false,
      _base: cat?.computersAndLaptop,
    },
    {
      _id: 2009,
      name: "VIOMI V2 Pro LDS Sensor 2 In 1 Sweeping Mopping Robot Wet And Dry Vacuum Cleaner 2100Pa Strong Suction Self-Charging",
      images: [
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 450,
      discountedPrice: 380,
      quantity: 1,
      rating: 4.2,
      reviews: 70,
      category: "Robot Clean",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Robot Clean",
      isNew: true,
      _base: cat?.robotClean,
    },
    {
      _id: 2010,
      name: "Global Version Redmi Note 9 Pro 6GB RAM 64GB ROM Smartphone Mobile Phone",
      images: [
        "https://i.ibb.co/sK9yYnY/phone.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 305,
      discountedPrice: 285,
      quantity: 1,
      rating: 4.1,
      reviews: 160,
      category: "Cell Phones",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Cual Sim Phones",
      isNew: true,
      _base: cat?.cellPhones,
    },
    {
      _id: 2011,
      name: "DIDSeth Pan Tilt Security Light Camera Full HD 1080P Wireless Wi-Fi IP Camera Home Dome Surveillance Cameras",
      images: [
        "https://i.ibb.co/SX8wF1V/camera.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 350,
      discountedPrice: 280,
      quantity: 1,
      rating: 3.8,
      reviews: 250,
      category: "Cameras & Photos",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Security & Protection",
      isNew: true,
      _base: cat?.camerasAndPhotos,
    },
    {
      _id: 2012,
      name: "Electric Hot Melt Glue Gun Cordless Repair DIY Tool Heating Mini Glue Gun With Glue Sticks",
      images: [
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 150,
      discountedPrice: 80,
      quantity: 1,
      rating: 4.7,
      reviews: 90,
      category: "Power Tools",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Power Tools",
      isNew: true,
      _base: cat?.powerTools,
    },
    {
      _id: 2013,
      name: "MECOOL KH3 Android 10.0 Smart 4K 60fps TV Box – Black 2GB RAM + 16GB ROM",
      images: [
        "https://i.ibb.co/vqmLWww/tvBox.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 210,
      discountedPrice: 200,
      quantity: 1,
      rating: 3.9,
      reviews: 100,
      category: "TV Box",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "TV Box",
      isNew: true,
      _base: cat?.tvBox,
    },
    {
      _id: 2014,
      name: "Sony PS4 Controller Bluetooth Vibration Gamepad For Playstation 4 Detroit Wireless Joystick For PS4 Games Consol",
      images: [
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 80,
      discountedPrice: 75,
      quantity: 1,
      rating: 4.2,
      reviews: 110,
      category: "Game and Video",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Game & Video",
      isNew: true,
      _base: cat?.gameAndVideo,
    },
    {
      _id: 2015,
      name: "GSR 120-Li Hand Drill 12V Lithium Drill Household Power Tool Screwdriver With One Battery – GSR120-LI 1Battery",
      images: [
        "https://i.ibb.co/NxM3M4g/hand-Drill.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 560,
      discountedPrice: 400,
      quantity: 1,
      rating: 4,
      reviews: 300,
      category: "Power Tools",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Power Tools",
      isNew: true,
      _base: cat?.powerTools,
    },
    {
      _id: 2016,
      name: "Xiaomi Mi Outdoor Speaker Bluetooth 5.0 IP55 Waterproof Dustproof Portable Wireless Speaker",
      images: [
        "https://i.ibb.co/PMDZZPY/bluetooth-Speaker.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 250,
      discountedPrice: 240,
      quantity: 1,
      rating: 4.2,
      reviews: 110,
      category: "TV and Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Blutooth Speakers",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2017,
      name: "Global Version Mi TV Stick Android TV 9.0 Smart 2K HDR 1GB RAM 8GB ROM Bluetooth 4.2 Mini TV Dongle",
      images: [
        "https://i.ibb.co/GvBj7SV/usb.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 60,
      discountedPrice: 55,
      quantity: 1,
      rating: 4,
      reviews: 100,
      category: "TV Box",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "TV Box",
      isNew: true,
      _base: cat?.tvBox,
    },
    {
      _id: 2018,
      name: "Xiaomi Mijia LCD Writing Tablet With Pen 10 13.5inch Digital Drawing Message Graphics Electronic Handwriting Pad With Pen",
      images: [
        "https://i.ibb.co/fxJkDbC/writing-Tablet.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 350,
      discountedPrice: 330,
      quantity: 1,
      rating: 4.2,
      reviews: 70,
      category: "Tablets",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Tablets",
      isNew: true,
      _base: cat?.tablets,
    },
    {
      _id: 2019,
      name: "New Creative Cloth Art Home Outdoors Bluetooth Sound Box",
      images: [
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 120,
      discountedPrice: 100,
      quantity: 1,
      rating: 4.1,
      reviews: 20,
      category: "Bluetooth Speakers",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Bluetooth Speakers",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2020,
      name: "Global Version Redmi Note 9 Pro 6GB RAM 64GB ROM Smartphone Mobile Phone",
      images: [
        "https://i.ibb.co/WyvSw8N/phoneTwo.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 450,
      discountedPrice: 410,
      quantity: 1,
      rating: 3.7,
      reviews: 190,
      category: "Cell Phones",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Dual Sim Phones",
      isNew: true,
      _base: cat?.cellPhones,
    },
    {
      _id: 2021,
      name: "L21 Bluetooth Earphone Wireless Earbuds 5.0 TWS Headsets Dual Earbuds Bass Sound For Huawei Xiaomi IPhone Samsung Mobile Phones",
      images: [
        "https://i.ibb.co/vjrLRfV/earbuds.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 350,
      discountedPrice: 320,
      quantity: 1,
      rating: 3.9,
      reviews: 10,
      category: "Headphones",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Fitness Headphones",
      isNew: true,
      _base: cat?.headphones,
    },
    {
      _id: 2022,
      name: "Roborock S7 Robot Vacuum Cleaner For Home Sonic Mopping Ultrasonic Carpet Clean Alexa Mop Lifting Upgrade For S5 Max",
      images: [
        "https://i.ibb.co/09ySKVm/vaccum-Cleaner.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 250,
      discountedPrice: 240,
      quantity: 1,
      rating: 4.2,
      reviews: 100,
      category: "Robot Clean",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Robot Clean",
      isNew: true,
      _base: cat?.robotClean,
    },
    {
      _id: 2023,
      name: "Klipsch R-120SW Powerful Detailed Home Speaker – Unit",
      images: [
        "https://i.ibb.co/bR9LcZY/home-Speaker.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 600,
      discountedPrice: 580,
      quantity: 1,
      rating: 4.7,
      reviews: 200,
      category: "TV & Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Bluetooth Speaker",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2024,
      name: "ZY418 Ultra-Thin Sport MP3 MP4 Music Player",
      images: [
        "https://i.ibb.co/f9GKwRd/mp3-Player.webp",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 80,
      discountedPrice: 70,
      quantity: 1,
      rating: 4.2,
      reviews: 60,
      category: "TV & Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "MP3 Player",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2025,
      name: "Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band",
      images: [
        "https://i.ibb.co/9hHGFnT/watchTwo.jpg",
        "https://i.ibb.co/m6ZN7LX/soundBox.webp",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 220,
      discountedPrice: 210,
      quantity: 1,
      rating: 4.5,
      reviews: 90,
      category: "Smart Watches",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Smart Health Watch",
      isNew: true,
      _base: cat?.smartWatches,
    },
  ];



// export const highlightsProducts = [
//     {
//         _id: 3001,
//         name: "New Deals at Best Prices",
//         title: "From $40.00",
//         image: "https://i.ibb.co/G951N5B/highlights-One.webp",
//         _base: "/products",
//         color: "#000000",
//     },
//     {
//         _id: 3002,
//         name: "Hot Deals at Affordable Prices",
//         title: "From $20.00",
//         image: "https://slot.ng/media/catalog/product/cache/7cc17357a06f829e544a54ed5a492e71/i/p/iphone_2.jpg",
//         _base: "/products",
//         color: "#000000",
//     },
//     {
//         _id: 3003,
//         name: "Lastest Product with 10% Discount",
//         title: "From $250.00",
//         image: "https://banner2.cleanpng.com/20180604/bv/kisspng-measuring-scales-coffeemaker-techcity-pk-sota-khar-weighing-machine-5b15433613d2e9.0061647715281201180812.jpg",
//         _base: "/products",
//         color: "#000000",
//     },
//     {
//         _id: 3003,
//         name: "Lastest Product with 10% Discount",
//         title: "From $25.00",
//         image: "https://banner2.cleanpng.com/20180604/bv/kisspng-measuring-scales-coffeemaker-techcity-pk-sota-khar-weighing-machine-5b15433613d2e9.0061647715281201180812.jpg",
//         _base: "/products",
//         color: "#000000",
//     },
//     {
//         _id: 3004,
//         name: "Hot Deals",
//         title: "From $40.00",
//         image: "https://5.imimg.com/data5/SELLER/Default/2021/3/UG/OC/RS/125339512/wireless-home-theater-500x500.jpg",
//         _base: "/products",
//         color: "#000000",
//     },
// ]
// export const blogsData = [
//     {
//         _id: 4001,
//         image: "https://www.gta.net/hubfs/consumer/products/samsung-galaxy-S24-ultra-color/samsung-galaxy-s24-ultra-Titanium%20Gray.png",
//         title: "lastest SamSung is available now",
//         _base: "technology",
//         description: "it has USB Interface: USB Type-C, USB Version: USB 3.2 Gen 1, Location Technology: GPS, Glonass, Beidou, Galileo, QZSS. Earjack: USB Type-C, MHL: No, 802.11a/b/g/n/ac/ax/be 2.4GHz+5GHz+6GHz, EHT320, MIMO, 4096-QAM, Wi-Fi Direct: Yes, Bluetooth Version: Bluetooth v5.3."
//     },
//     {
//         _id: 4002,
//         image: "https://www.goldgenie.com/wp-content/uploads/2024/08/Luxury-Platinum-iPhone-16-Pro-Pro-Max.webp",
//         title: "lastest Iphone now available",
//         _base: "technology",
//         description: "it has some many amazing features you can't resist."
//     },
// ]
// export const products = [
//     {
//         _id: 2001,
//         name: "High bluetooth speakers",
//         images: [
//             "https://cdn.mos.cms.futurecdn.net/Lj4KzFENVv9bYRFbPhcTgV-320-80.png",
//             "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaWy-f0wovXjKBIHHk6kYU9_sjZ9WztuaQkRkIoGKChog1OnanRv_7YAs_uZjvDlqZN2k&usqp=CAU",
//             "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdotwYBNcSxgKQbcYb5NNZKRzMlATYGEUVRl1OdBWvcwrD7PFd-yFi93Yh-3gXoEfzv0Q&usqp=CAU",
//             "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQci5Lk5ytezLGF9Rq06fmuONwc0qPT0K5VmCBHTi3QdUgcyqpSql92o_d4qr_cfWzWHbg&usqp=CAU",
//             "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3VanwpovXxoRHXyRSMwB5L0z8t1Zci8Q89Q&s"
//         ],
//         description: "Top quality bass speakers with different play mode to suit your desires",
//         regularPrice: 600,
//         discountedPrice: 400,
//         quantity: 1,
//         rating: 4.5,
//         reviews: 50,
//         category: "Air Pod",
//         colors: ["blue", "black", "cream", "sliver", "ash"],
//         Brand: "Bose",
//         isStock: true,
//         overview: "Bluetooth Speaker",
//         isNew: "true",
//         _base: cat?.tvAndAudio,
//     },
//     {
//         _id: 2002,
//         name: "Pro 5 Air Pod",
//         images: [
//            "https://www.apple.com/newsroom/images/product/airpods/standard/Apple_AirPods-3rd-gen_hero_10182021.jpg.news_app_ed.jpg",
//             "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT188k2G4VcQ2-DfCwyn-79yiL1Z1OburuzGQ&s",
//             "https://cdn.luxuo.com/2019/11/660-caviar_airpods_pro_gold_3_mpage_a-copy.jpg",
//         ],
//         description: "Top quality bluetooth airpod with long last battery and deep bass",
//         regularPrice: 80,
//         discountedPrice: 50,
//         quantity: 1,
//         rating: 4.8,
//         reviews: 30,
//         category: "TV & Audio",
//         colors: ["white", "black", "gold"],
//         Brand: "Apple",
//         isStock: true,
//         overview: "Bluetooth Speaker",
//         isNew: "true",
//         _base: cat?.airPod,
//     },
// ]